CREATE SCHEMA rinha;

CREATE UNLOGGED TABLE rinha.clientes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    saldo integer NOT NULL,
    limite integer NOT NULL,
    CONSTRAINT pk_clientes PRIMARY KEY (id)
);

CREATE UNLOGGED TABLE rinha.transacoes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cliente_id integer NOT NULL,
    valor integer NOT NULL,
    tipo character(1) NOT NULL,
    descricao text,
    realizada_em timestamp without time zone NOT NULL,
    CONSTRAINT pk_transacoes PRIMARY KEY (id)
);

INSERT INTO rinha.clientes (id, limite, saldo)
VALUES (1, 100000, 0);
INSERT INTO rinha.clientes (id, limite, saldo)
VALUES (2, 80000, 0);
INSERT INTO rinha.clientes (id, limite, saldo)
VALUES (3, 1000000, 0);
INSERT INTO rinha.clientes (id, limite, saldo)
VALUES (4, 10000000, 0);
INSERT INTO rinha.clientes (id, limite, saldo)
VALUES (5, 500000, 0);

SELECT setval(
    pg_get_serial_sequence('rinha.clientes', 'id'),
    GREATEST(
        (SELECT MAX(id) FROM rinha.clientes) + 1,
        nextval(pg_get_serial_sequence('rinha.clientes', 'id'))),
    false);


pg_advisory_xact_lock
